[project]
name = "mlmc-linear-systems"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "nealkuperman", email = "nealwkuperman@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "numpy>=2.5.2",
    "scipy>=1.18.0",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[dependency-groups]
dev = [
    "pytest>=9.1.1",
]
